### ISSUE TITLE
task-5-insert_database_data

### ISSUE THREAD

**Issue by MichiasShiferaw** [MichiasShiferaw/database-proj#6]
## Task 5

Complete each requirement:

- [ ] Insert in your database data for each one of the 5 hotel chains. 
- [ ] Each hotel chain of them has at least 8 hotels, which belong to at least 3 categories. 
- [ ] Two of the hotels at least should be in the same area. 
- [ ] Each hotel should have at least 5 rooms of different capacity.
